### ISSUE TITLE
killSignal behaviour

### ISSUE THREAD

**Issue by franciscocpg** [codeskyblue/fswatch#12]
Why [killSignal](https://github.com/codeskyblue/fswatch/blob/master/fswatch.go#L89) cannot be configured using `.fsw.yml` and it is being forced to `SIGKILL`?

**Comment by codeskyblue** [comment]
which system you are using.  linux  mac or windows?

**Comment by codeskyblue** [comment]
more details, your information provided are too inficient

**Comment by codeskyblue** [comment]
insufficient

**Comment by codeskyblue** [comment]
[Signal](https://github.com/codeskyblue/fswatch/blob/master/fswatch.go#L88) can be configured.

**Comment by franciscocpg** [comment]
Yes, but `Signal` it works only when we edit and save something.
When we press `CTRL+C` it uses `killSignal` and sends `SIGKILL` .
By doing this my program only receives the proper `signal` notify when I edit/save something, but not when I press `CTRL+C` using fsw.

**Comment by codeskyblue** [comment]
yes, you are right, when edit something, program accept signal, only reload, sometime not quit. But when press `CTRL+C` fswatch exited, so at that moment, it is better to clean the environment which mean kill all running program. That's why send `SIGKILL`

**Comment by franciscocpg** [comment]
Right, but why can't this be an option to the user?
At I mentioned here https://github.com/codeskyblue/fswatch/issues/12#issuecomment-230768549, my program is not stopping properly and because of that I can't use `fsw` (which is a wonderful too) for develop.
Can I propose a PR?

**Comment by codeskyblue** [comment]
year, add an option seems a good way, pr is welcome.
