### ISSUE TITLE
Passing matches down to command

### ISSUE THREAD

**Issue by iilyak** [codeskyblue/fswatch#13]
This is a feature request. 
Would it be possible to pass a list of files which were updated to the command.
Or provide an option to execute command for every event and pass the name of a file to the command as well.

**Comment by codeskyblue** [comment]
welcome for pr

**Comment by iilyak** [comment]
I wouldn't be able to do the PR due to lack of permission to contribute to the project from my employer.

**Comment by codeskyblue** [comment]
@iilyak This project is created in after work time. My employer is not allowed too.

**Comment by iilyak** [comment]
:-)
