### ISSUE TITLE
Can't seem to ignore a path.

### ISSUE THREAD

**Issue by nerdyworm** [codeskyblue/fswatch#19]
Good evening,

I can't seem to ignore an entire directory.  I've tried several patterns and they all seem to fail me.
```
  pattens:
  - '**/*.go'
  - '!./frontend/'
```

Basically what happens is that it starts watching frontend/node_modules and then explodes with too many open files.

Is there a way to configure this so that it does not walk that directory?

**Comment by codeskyblue** [comment]
Reopen if you have more questions

**Comment by nerdyworm** [comment]
Thank you!  Works like a charm!
