### ISSUE TITLE
fswatch to watch multiple file types with specified actions on those files' changes

### ISSUE THREAD

**Issue by rhacker** [codeskyblue/fswatch#2]
Hi there,
I don't know if it's possible to run one fswatch session to have multiple actions based on a set of filetypes. For example:
```
(sass|scss) : sass ...
(jade) : jade ..
(cc): gcc ...
```

thanks for the nice tool :)

**Comment by codeskyblue** [comment]
This issue has been opened for two years. ^_^ fixed now.
