### ISSUE TITLE
Not backwards compatible

### ISSUE THREAD

**Issue by crholm** [codeskyblue/fswatch#25]
More of an FYI

the commit fe2525c3b867b85320c5a70e5cb15400c6d493aa from 12 days ago broke our dev environment, since we have our fsw.yml file in specific locations and use `-config` for that.

Not really an issue for us, forking and rolling back works fine. But a somewhat alienating experience.

**Comment by codeskyblue** [comment]
Thanks for your issue, which let me know this repo is still have users (I ever thought this repo is died).
A few days ago, I try to use fswatch to debug code, but this usage looks quite complicated. so I try to make it more simple to use. Putting the command through command line (not in fsw.yml), eg: `fswatch python -u test.py`

I'm tring to add it back.

**Comment by codeskyblue** [comment]
add back in https://github.com/codeskyblue/fswatch/commit/a07fa02ded7bab2a9a5b664f1ce0a873b3908e0e

**Comment by crholm** [comment]
Thank you :) much appreciated. It workes well.
