### ISSUE TITLE
Vagrant

### ISSUE THREAD

**Issue by drewwells** [codeskyblue/fswatch#3]
I'm using NFS with vagrant to build a project. Modifying files on the host doesn't get picked up inside the guest. Is there any support for these type of events?

**Comment by drewwells** [comment]
It appears this is not possible, and most libraries implement this functionality via polling.

**Comment by jephir** [comment]
`fswatch` will work if you use [RSync Synced Folders](https://docs.vagrantup.com/v2/synced-folders/rsync.html) in Vagrant.
