### ISSUE TITLE
Too many opened files

### ISSUE THREAD

**Issue by alehano** [codeskyblue/fswatch#4]
```
I have an error - fswatch >>> too many open files
Config like so:
{
    "paths": [
        "/path/to/project"
    ],
    "depth": 5,
    "exclude": [],
    "include": [
        "\\.(go|tmpl)$"
    ],
    "command": "echo helloworld",
    "env": {
        "POWERD_BY": "github.com/codeskyblue/fswatch"
    },
    "autorestart": false,
    "restart-interval": 0,
    "kill-signal": "KILL"
}
```

If I set depth to 2, all works. But I want deeper nesting. 
It seems to fswatch open all files, not only that in "include" 
I have folder ./static/ which has many files. How can I excude it?

**Comment by codeskyblue** [comment]
One answer from stackoverflow: <http://stackoverflow.com/questions/20901518/ubuntu-too-many-open-files>
